### ISSUE TITLE
`frameType` values in `TimeFrame`

### ISSUE THREAD

**Issue by keighrim** [clamsproject/mmif#207]
Currently a set of values are specified in the vocab as 
https://github.com/clamsproject/mmif/blob/79c621f5c3dabb499a0878f30a59ca25b56bbb5d/vocabulary/clams.vocabulary.yaml#L140

But we already have apps that generate `frameType=bars`, `frameType=tone`, `frameType=chyron`,  and possibly many more to come. Should we relax the prose in the type definition and explicitly say the value can be anything? 

** regarding `chyron`, [I raised a question](https://github.com/clamsproject/app-chyron-text-recognition/pull/3#discussion_r1237956876) about its appropriateness, compared to non-proper noun-based `lower-third`. In addition to that question, we might also want to think about how to handle synonyms and their normalization (to one representative value).

**Comment by marcverhagen** [comment]
We could add the newly introduced values, but also make clear that it is not an exhaustive list:

```yaml
properties:
  frameType:
    type: String
    description: The type of TimeFrame. Possible values include, but are not limited to, bars-and-tones, speech, noise, music, other, bars, tone, chyron and credits.
```
